#include "boost/capy/ex/this_coro.hpp"
#include "utils.hpp"

#include "../echo_handler.hpp"

#include <nghttp2-corosio/client.hpp>
#include <nghttp2-corosio/server.hpp>

#include <boost/capy/buffers/make_buffer.hpp>
#include <boost/capy/cond.hpp>
#include <boost/capy/ex/run_async.hpp>
#include <boost/corosio/ipv4_address.hpp>
#include <boost/corosio/tls_context.hpp>

#include <gtest/gtest.h>

#include <array>
#include <cstdint>
#include <string>
#include <string_view>
#include <system_error>
#include <utility>

namespace capy = boost::capy;
namespace corosio = boost::corosio;

namespace
{

// Certificate chain generated by test/pki/create.sh (see test/CMakeLists.txt), rooted at
// test/pki/out/root.pem -- paths are relative to the repo root, matching this test binary's
// WORKING_DIRECTORY (see test/CMakeLists.txt's gtest_discover_tests() call).

corosio::tls_context make_server_tls_context()
{
   corosio::tls_context ctx;
   ctx.use_certificate_chain_file("test/pki/out/server-fullchain.pem");
   ctx.use_private_key_file("test/pki/out/server-key.pem", corosio::tls_file_format::pem);
   ctx.set_alpn({"h2", "http/1.1"});
   return ctx;
}

corosio::tls_context make_client_tls_context()
{
   corosio::tls_context ctx;
   ctx.load_verify_file("test/pki/out/root.pem");
   ctx.set_verify_mode(corosio::tls_verify_mode::peer);
   ctx.set_alpn({"h2", "http/1.1"});
   return ctx;
}

// Same shape as ClientTest.EchoesRequestBody in test_client.cpp, but connecting over TLS -- see
// that test for why this is a free (non-capturing-lambda) coroutine.
capy::task<> echo_request_tls(std::uint16_t port, std::string_view payload, std::string& echoed,
                                     bool& ok)
{
   auto ex = co_await capy::this_coro::executor;
   auto ep = corosio::endpoint(corosio::ipv4_address("127.0.0.1"), port);
   nghttp2_corosio::Client client(ex);
   auto [ec, session] = co_await client.connect(ep, make_client_tls_context(), "localhost");
   if (ec)
      co_return;

   auto [sec, request] = co_await session.submit_request("/echo");
   if (sec)
      co_return;

   auto [wec, wn] = co_await request.write_eof(capy::make_buffer(payload));

   auto [gec, reader] = co_await request.get_response();
   if (gec)
      co_return;

   std::error_code rec;
   std::array<char, 1024> buffer;
   for (;;)
   {
      auto [rec_ec, n] = co_await reader.read_some(capy::make_buffer(buffer));
      echoed.append(buffer.data(), n);
      if (rec_ec)
      {
         // Reaching end-of-stream is how this loop is meant to end -- not a failure to report.
         if (rec_ec != capy::cond::eof)
            rec = rec_ec;
         break;
      }
   }

   ok = !wec && !rec;
}

} // namespace

namespace
{

// DISABLED: deadlocks on a confirmed bug in corosio's openssl_stream backend, not in this
// project. recv_loop()/send_loop() concurrently read_some()/write_some() the same any_stream (by
// design -- this already works for plaintext sockets), but openssl_stream::impl serializes both
// directions behind one io_cm_ async_mutex, and read_input() (called when SSL_read needs more
// ciphertext) holds that mutex across a blocking socket-level read. If the peer has nothing more
// to send -- which is the normal case here, since the client is waiting for our response --
// that read never completes, so flush_output() (needed to send the already-ready response) can
// never acquire the same mutex to write anything. Confirmed independent of nghttp2-corosio with
// a minimal standalone repro (server+client openssl_stream, no nghttp2 involved) hitting the
// identical deadlock. Re-enable once corosio fixes this (or provides a backend that doesn't
// serialize read/write through one lock held across a blocking op).
TEST(TlsTest, DISABLED_EchoesRequestBodyOverTls)
{
   nghttp2_corosio::Config config;
   config.port = 0; // ask the OS for an unused port
   config.handler = echo_handler;
   config.tls = make_server_tls_context();
   nghttp2_corosio::Server server(config);
   auto port = server.local_endpoint().port();

   constexpr std::string_view payload = "hello over TLS!";
   std::string echoed;
   bool ok = false;

   capy::run_async(server.get_executor(), [&server] { server.stop(); },
                          [&server](std::exception_ptr) { server.stop(); })(
      echo_request_tls(port, payload, echoed, ok));

   nghttp2_corosio_test::run(server.get_executor().context());

   EXPECT_TRUE(ok);
   EXPECT_EQ(echoed, payload);
}

} // namespace
